/*
 * Sanmargar Data Transformation Tools
 *
 * (C) Copyright 2015 Sanmargar Team sp z o. o. (http://sanmargar.pl/) and others.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/
package pl.sanmargar.sdtt;
import java.util.HashMap;
import java.util.ArrayList;

public class UrzedySkarbowe {
	public final static ArrayList<String> fakeNipMap = new ArrayList<String>();
	static {
		fakeNipMap.add("1111111111");
		fakeNipMap.add("2222222222");
		fakeNipMap.add("3333333333");
		fakeNipMap.add("4444444444");
		fakeNipMap.add("5555555555");
		fakeNipMap.add("6666666666");
		fakeNipMap.add("7777777777");
		fakeNipMap.add("8888888888");
		fakeNipMap.add("9999999999");
	}
	public final static HashMap<String, String> urzedySkarboweMap = new HashMap<String, String>();
	static {
		urzedySkarboweMap.put("101","Dolnośląski Urząd Skarbowy we Wrocławiu");
		urzedySkarboweMap.put("102","Kujawsko-Pomorski Urząd Skarbowy w Bydgoszczy");
		urzedySkarboweMap.put("103","Lubelski Urząd Skarbowy w Lublinie");
		urzedySkarboweMap.put("104","Lubuski Urząd Skarbowy w Zielonej Górze");
		urzedySkarboweMap.put("105","Łódzki Urząd Skarbowy w Łodzi");
		urzedySkarboweMap.put("106","Małopolski Urząd Skarbowy w Krakowie");
		urzedySkarboweMap.put("107","Pierwszy Mazowiecki Urząd Skarbowy w Warszawie");
		urzedySkarboweMap.put("108","Drugi Mazowiecki Urząd Skarbowy w Warszawie");
		urzedySkarboweMap.put("109","Trzeci Mazowiecki Urząd Skarbowy w Radomiu");
		urzedySkarboweMap.put("111","Urząd Skarbowy Warszawa-Mokotów");
		urzedySkarboweMap.put("112","Urząd Skarbowy Warszawa-Bemowo");
		urzedySkarboweMap.put("113","Urząd Skarbowy Warszawa-Praga");
		urzedySkarboweMap.put("114","Urząd Skarbowy Warszawa-Targówek");
		urzedySkarboweMap.put("115","Pierwszy Urząd Skarbowy Warszawa-Śródmieście");
		urzedySkarboweMap.put("116","Drugi Urząd Skarbowy Warszawa-Śródmieście");
		urzedySkarboweMap.put("117","Urząd Skarbowy Warszawa-Wola");
		urzedySkarboweMap.put("118","Urząd Skarbowy Warszawa-Bielany");
		urzedySkarboweMap.put("119","Urząd Skarbowy w Grodzisku Mazowieckim");
		urzedySkarboweMap.put("121","Urząd Skarbowy w Nowym Dworze Mazowieckim");
		urzedySkarboweMap.put("122","Urząd Skarbowy w Otwocku");
		urzedySkarboweMap.put("123","Urząd Skarbowy w Piasecznie");
		urzedySkarboweMap.put("124","Urząd Skarbowy w Pruszkowie");
		urzedySkarboweMap.put("125","Urząd Skarbowy w Wołominie");
		urzedySkarboweMap.put("126","Urząd Skarbowy w Białej Podlaskiej");
		urzedySkarboweMap.put("127","Urząd Skarbowy w Parczewie");
		urzedySkarboweMap.put("128","Urząd Skarbowy w Radzyniu Podlaskim");
		urzedySkarboweMap.put("129","Pierwszy Urząd Skarbowy w Białymstoku");
		urzedySkarboweMap.put("131","Urząd Skarbowy w Bielsku Podlaskim");
		urzedySkarboweMap.put("132","Urząd Skarbowy w Mońkach");
		urzedySkarboweMap.put("133","Urząd Skarbowy w Siemiatyczach");
		urzedySkarboweMap.put("134","Urząd Skarbowy w Sokółce");
		urzedySkarboweMap.put("135","Pierwszy Urząd Skarbowy w Bielsku-Białej");
		urzedySkarboweMap.put("136","Urząd Skarbowy w Cieszynie");
		urzedySkarboweMap.put("137","Urząd Skarbowy w Oświęcimiu");
		urzedySkarboweMap.put("138","Urząd Skarbowy w Suchej Beskidzkiej");
		urzedySkarboweMap.put("139","Urząd Skarbowy w Wadowicach");
		urzedySkarboweMap.put("141","Urząd Skarbowy w Żywcu");
		urzedySkarboweMap.put("142","Pierwszy Urząd Skarbowy w Bydgoszczy");
		urzedySkarboweMap.put("143","Urząd Skarbowy w Chojnicach");
		urzedySkarboweMap.put("144","Urząd Skarbowy w Inowrocławiu");
		urzedySkarboweMap.put("145","Urząd Skarbowy w Mogilnie");
		urzedySkarboweMap.put("146","Urząd Skarbowy w Nakle nad Notecią");
		urzedySkarboweMap.put("147","Urząd Skarbowy w Świeciu");
		urzedySkarboweMap.put("148","Urząd Skarbowy w Tucholi");
		urzedySkarboweMap.put("149","Urząd Skarbowy w Żninie");
		urzedySkarboweMap.put("151","Urząd Skarbowy w Chełmie");
		urzedySkarboweMap.put("152","Urząd Skarbowy w Krasnymstawie");
		urzedySkarboweMap.put("153","Urząd Skarbowy we Włodawie");
		urzedySkarboweMap.put("154","Urząd Skarbowy w Ciechanowie");
		urzedySkarboweMap.put("155","Urząd Skarbowy w Działdowie");
		urzedySkarboweMap.put("156","Urząd Skarbowy w Mławie");
		urzedySkarboweMap.put("157","Urząd Skarbowy w Płońsku");
		urzedySkarboweMap.put("158","Urząd Skarbowy w Pułtusku");
		urzedySkarboweMap.put("159","Pierwszy Urząd Skarbowy w Częstochowie");
		urzedySkarboweMap.put("161","Urząd Skarbowy w Kłobucku");
		urzedySkarboweMap.put("162","Urząd Skarbowy w Lublińcu");
		urzedySkarboweMap.put("163","Urząd Skarbowy w Myszkowie");
		urzedySkarboweMap.put("164","Urząd Skarbowy w Oleśnie");
		urzedySkarboweMap.put("165","Urząd Skarbowy w Braniewie");
		urzedySkarboweMap.put("166","Urząd Skarbowy w Elblągu");
		urzedySkarboweMap.put("167","Urząd Skarbowy w Kwidzynie");
		urzedySkarboweMap.put("168","Urząd Skarbowy w Malborku");
		urzedySkarboweMap.put("169","Pierwszy Urząd Skarbowy w Gdańsku");
		urzedySkarboweMap.put("171","Drugi Urząd Skarbowy w Gdańsku");
		urzedySkarboweMap.put("172","Pierwszy Urząd Skarbowy w Gdyni");
		urzedySkarboweMap.put("173","Urząd Skarbowy w Kartuzach");
		urzedySkarboweMap.put("174","Urząd Skarbowy w Kościerzynie");
		urzedySkarboweMap.put("175","Urząd Skarbowy w Pucku");
		urzedySkarboweMap.put("176","Urząd Skarbowy w Sopocie");
		urzedySkarboweMap.put("177","Urząd Skarbowy w Starogardzie Gdańskim");
		urzedySkarboweMap.put("178","Urząd Skarbowy w Tczewie");
		urzedySkarboweMap.put("179","Urząd Skarbowy w Wejherowie");
		urzedySkarboweMap.put("181","Urząd Skarbowy w Choszcznie");
		urzedySkarboweMap.put("182","Urząd Skarbowy w Gorzowie Wielkopolskim");
		urzedySkarboweMap.put("183","Urząd Skarbowy w Myśliborzu");
		urzedySkarboweMap.put("184","Urząd Skarbowy w Międzychodzie");
		urzedySkarboweMap.put("185","Urząd Skarbowy w Międzyrzeczu");
		urzedySkarboweMap.put("186","Urząd Skarbowy w Słubicach");
		urzedySkarboweMap.put("187","Urząd Skarbowy w Bolesławcu");
		urzedySkarboweMap.put("188","Urząd Skarbowy w Jeleniej Górze");
		urzedySkarboweMap.put("189","Urząd Skarbowy w Kamiennej Górze");
		urzedySkarboweMap.put("191","Urząd Skarbowy w Lubaniu");
		urzedySkarboweMap.put("192","Urząd Skarbowy w Lwówku Śląskim");
		urzedySkarboweMap.put("193","Urząd Skarbowy w Zgorzelcu");
		urzedySkarboweMap.put("194","Urząd Skarbowy w Jarocinie");
		urzedySkarboweMap.put("195","Pierwszy Urząd Skarbowy w Kaliszu");
		urzedySkarboweMap.put("196","Urząd Skarbowy w Kępnie");
		urzedySkarboweMap.put("197","Urząd Skarbowy w Krotoszynie");
		urzedySkarboweMap.put("198","Urząd Skarbowy w Ostrowie Wielkopolskim");
		urzedySkarboweMap.put("199","Urząd Skarbowy w Będzinie");
		urzedySkarboweMap.put("201","Opolski Urząd Skarbowy w Opolu");
		urzedySkarboweMap.put("202","Podkarpacki Urząd Skarbowy w Rzeszowie");
		urzedySkarboweMap.put("203","Podlaski Urząd Skarbowy w Białymstoku");
		urzedySkarboweMap.put("204","Pomorski Urząd Skarbowy w Gdańsku");
		urzedySkarboweMap.put("205","Pierwszy Śląski Urząd Skarbowy w Sosnowcu");
		urzedySkarboweMap.put("206","Drugi Śląski Urząd Skarbowy w Bielsku-Białej");
		urzedySkarboweMap.put("207","Świętokrzyski Urząd Skarbowy w Kielcach");
		urzedySkarboweMap.put("208","Warmińsko-Mazurski Urząd Skarbowy w Olsztynie");
		urzedySkarboweMap.put("209","Pierwszy Wielkopolski Urząd Skarbowy w Poznaniu");
		urzedySkarboweMap.put("211","Urząd Skarbowy w Bytomiu");
		urzedySkarboweMap.put("212","Urząd Skarbowy w Chorzowie");
		urzedySkarboweMap.put("213","Urząd Skarbowy w Chrzanowie");
		urzedySkarboweMap.put("214","Urząd Skarbowy w Czechowicach-Dziedzicach");
		urzedySkarboweMap.put("215","Urząd Skarbowy w Dąbrowie Górniczej");
		urzedySkarboweMap.put("216","Pierwszy Urząd Skarbowy w Gliwicach");
		urzedySkarboweMap.put("217","Urząd Skarbowy w Jastrzębiu-Zdroju");
		urzedySkarboweMap.put("218","Urząd Skarbowy w Jaworznie");
		urzedySkarboweMap.put("219","Pierwszy Urząd Skarbowy w Katowicach");
		urzedySkarboweMap.put("221","Urząd Skarbowy w Mikołowie");
		urzedySkarboweMap.put("222","Urząd Skarbowy w Mysłowicach");
		urzedySkarboweMap.put("223","Urząd Skarbowy w Olkuszu");
		urzedySkarboweMap.put("224","Urząd Skarbowy w Pszczynie");
		urzedySkarboweMap.put("225","Urząd Skarbowy w Raciborzu");
		urzedySkarboweMap.put("226","Urząd Skarbowy w Rudzie Śląskiej");
		urzedySkarboweMap.put("227","Urząd Skarbowy w Rybniku");
		urzedySkarboweMap.put("228","Urząd Skarbowy w Siemianowicach Śląskich");
		urzedySkarboweMap.put("229","Urząd Skarbowy w Sosnowcu");
		urzedySkarboweMap.put("231","Urząd Skarbowy w Tarnowskich Górach");
		urzedySkarboweMap.put("232","Urząd Skarbowy w Tychach");
		urzedySkarboweMap.put("233","Urząd Skarbowy w Wodzisławiu Śląskim");
		urzedySkarboweMap.put("234","Urząd Skarbowy w Zabrzu");
		urzedySkarboweMap.put("235","Urząd Skarbowy w Zawierciu");
		urzedySkarboweMap.put("236","Urząd Skarbowy w Żorach");
		urzedySkarboweMap.put("237","Urząd Skarbowy w Busku-Zdroju");
		urzedySkarboweMap.put("238","Urząd Skarbowy w Jędrzejowie");
		urzedySkarboweMap.put("239","Pierwszy Urząd Skarbowy w Kielcach");
		urzedySkarboweMap.put("241","Urząd Skarbowy w Końskich");
		urzedySkarboweMap.put("242","Urząd Skarbowy w Miechowie");
		urzedySkarboweMap.put("243","Urząd Skarbowy w Ostrowcu Świętokrzyskim");
		urzedySkarboweMap.put("244","Urząd Skarbowy w Pińczowie");
		urzedySkarboweMap.put("245","Urząd Skarbowy w Starachowicach");
		urzedySkarboweMap.put("246","Urząd Skarbowy w Skarżysku-Kamiennej");
		urzedySkarboweMap.put("247","Urząd Skarbowy w Kole");
		urzedySkarboweMap.put("248","Urząd Skarbowy w Koninie");
		urzedySkarboweMap.put("249","Urząd Skarbowy w Słupcy");
		urzedySkarboweMap.put("251","Urząd Skarbowy w Turku");
		urzedySkarboweMap.put("252","Urząd Skarbowy w Białogardzie");
		urzedySkarboweMap.put("253","Urząd Skarbowy w Drawsku Pomorskim");
		urzedySkarboweMap.put("254","Urząd Skarbowy w Kołobrzegu");
		urzedySkarboweMap.put("255","Pierwszy Urząd Skarbowy w Koszalinie");
		urzedySkarboweMap.put("256","Urząd Skarbowy w Szczecinku");
		urzedySkarboweMap.put("257","Urząd Skarbowy Kraków-Krowodrza");
		urzedySkarboweMap.put("258","Urząd Skarbowy Kraków-Nowa Huta");
		urzedySkarboweMap.put("259","Urząd Skarbowy Kraków-Podgórze");
		urzedySkarboweMap.put("261","Urząd Skarbowy w Kraków-Śródmieście");
		urzedySkarboweMap.put("262","Urząd Skarbowy w Kraków-Stare Miasto");
		urzedySkarboweMap.put("263","Urząd Skarbowy w Myślenicach");
		urzedySkarboweMap.put("264","Urząd Skarbowy w Proszowicach");
		urzedySkarboweMap.put("265","Urząd Skarbowy w Wieliczce");
		urzedySkarboweMap.put("266","Urząd Skarbowy w Brzozowie");
		urzedySkarboweMap.put("267","Urząd Skarbowy w Jaśle");
		urzedySkarboweMap.put("268","Urząd Skarbowy w Krośnie");
		urzedySkarboweMap.put("269","Urząd Skarbowy w Lesku");
		urzedySkarboweMap.put("271","Urząd Skarbowy w Sanoku");
		urzedySkarboweMap.put("272","Urząd Skarbowy w Ustrzykach Dolnych");
		urzedySkarboweMap.put("273","Urząd Skarbowy w Głogowie");
		urzedySkarboweMap.put("274","Urząd Skarbowy w Jaworze");
		urzedySkarboweMap.put("275","Urząd Skarbowy w Legnicy");
		urzedySkarboweMap.put("276","Urząd Skarbowy w Lubinie");
		urzedySkarboweMap.put("277","Urząd Skarbowy w Złotoryi");
		urzedySkarboweMap.put("278","Urząd Skarbowy w Gostyniu");
		urzedySkarboweMap.put("279","Urząd Skarbowy w Kościanie");
		urzedySkarboweMap.put("281","Urząd Skarbowy w Lesznie");
		urzedySkarboweMap.put("282","Urząd Skarbowy w Rawiczu");
		urzedySkarboweMap.put("283","Urząd Skarbowy w Kraśniku");
		urzedySkarboweMap.put("284","Urząd Skarbowy w Lubartowie");
		urzedySkarboweMap.put("285","Pierwszy Urząd Skarbowy w Lublinie");
		urzedySkarboweMap.put("286","Drugi Urząd Skarbowy w Lublinie");
		urzedySkarboweMap.put("287","Urząd Skarbowy w Opolu Lubelskim");
		urzedySkarboweMap.put("288","Urząd Skarbowy w Puławach");
		urzedySkarboweMap.put("289","Urząd Skarbowy w Grajewie");
		urzedySkarboweMap.put("291","Urząd Skarbowy w Kolnie");
		urzedySkarboweMap.put("292","Urząd Skarbowy w Łomży");
		urzedySkarboweMap.put("293","Urząd Skarbowy w Wysokiem Mazowieckim");
		urzedySkarboweMap.put("294","Urząd Skarbowy w Zambrowie");
		urzedySkarboweMap.put("295","Urząd Skarbowy w Głownie");
		urzedySkarboweMap.put("296","Pierwszy Urząd Skarbowy Łódź-Bałuty");
		urzedySkarboweMap.put("297","Pierwszy Urząd Skarbowy Łódź-Górna");
		urzedySkarboweMap.put("298","Urząd Skarbowy Łódź-Polesie");
		urzedySkarboweMap.put("301","Drugi Wielkopolski Urząd Skarbowy w Kaliszu");
		urzedySkarboweMap.put("302","Zachodniopomorski Urząd Skarbowy w Szczecinie");
		urzedySkarboweMap.put("311","Urząd Skarbowy Łódź-Śródmieście");
		urzedySkarboweMap.put("312","Urząd Skarbowy Łódź-Widzew");
		urzedySkarboweMap.put("313","Urząd Skarbowy w Pabianicach");
		urzedySkarboweMap.put("314","Urząd Skarbowy w Zgierzu");
		urzedySkarboweMap.put("315","Urząd Skarbowy w Gorlicach");
		urzedySkarboweMap.put("316","Urząd Skarbowy w Limanowej");
		urzedySkarboweMap.put("317","Urząd Skarbowy w Nowym Sączu");
		urzedySkarboweMap.put("318","Urząd Skarbowy w Nowym Targu");
		urzedySkarboweMap.put("319","Urząd Skarbowy w Zakopanem");
		urzedySkarboweMap.put("321","Urząd Skarbowy w Bartoszycach");
		urzedySkarboweMap.put("322","Urząd Skarbowy w Iławie");
		urzedySkarboweMap.put("323","Urząd Skarbowy w Kętrzynie");
		urzedySkarboweMap.put("324","Urząd Skarbowy w Olsztynie");
		urzedySkarboweMap.put("325","Urząd Skarbowy w Ostródzie");
		urzedySkarboweMap.put("326","Urząd Skarbowy w Szczytnie");
		urzedySkarboweMap.put("327","Urząd Skarbowy w Brzegu");
		urzedySkarboweMap.put("328","Urząd Skarbowy w Głubczycach");
		urzedySkarboweMap.put("329","Urząd Skarbowy w Kędzierzynie-Koźlu");
		urzedySkarboweMap.put("331","Urząd Skarbowy w Kluczborku");
		urzedySkarboweMap.put("332","Urząd Skarbowy w Namysłowie");
		urzedySkarboweMap.put("333","Urząd Skarbowy w Nysie");
		urzedySkarboweMap.put("334","Pierwszy Urząd Skarbowy w Opolu");
		urzedySkarboweMap.put("335","Urząd Skarbowy w Prudniku");
		urzedySkarboweMap.put("336","Urząd Skarbowy w Strzelcach Opolskich");
		urzedySkarboweMap.put("337","Urząd Skarbowy w Makowie Mazowieckim");
		urzedySkarboweMap.put("338","Urząd Skarbowy w Ostrołęce");
		urzedySkarboweMap.put("339","Urząd Skarbowy w Ostrowi Mazowieckiej");
		urzedySkarboweMap.put("341","Urząd Skarbowy w Przasnyszu");
		urzedySkarboweMap.put("342","Urząd Skarbowy w Wyszkowie");
		urzedySkarboweMap.put("343","Urząd Skarbowy w Czarnkowie");
		urzedySkarboweMap.put("344","Urząd Skarbowy w Pile");
		urzedySkarboweMap.put("345","Urząd Skarbowy w Wałczu");
		urzedySkarboweMap.put("346","Urząd Skarbowy w Wągrowcu");
		urzedySkarboweMap.put("347","Urząd Skarbowy w Złotowie");
		urzedySkarboweMap.put("348","Urząd Skarbowy w Bełchatowie");
		urzedySkarboweMap.put("349","Urząd Skarbowy w Opocznie");
		urzedySkarboweMap.put("351","Urząd Skarbowy w Piotrkowie Trybunalskim");
		urzedySkarboweMap.put("352","Urząd Skarbowy w Radomsku");
		urzedySkarboweMap.put("353","Urząd Skarbowy w Tomaszowie Mazowieckim");
		urzedySkarboweMap.put("354","Urząd Skarbowy w Kutnie");
		urzedySkarboweMap.put("355","Urząd Skarbowy w Płocku");
		urzedySkarboweMap.put("356","Urząd Skarbowy w Sierpcu");
		urzedySkarboweMap.put("357","Urząd Skarbowy w Gnieźnie");
		urzedySkarboweMap.put("358","Urząd Skarbowy w Nowym Tomyślu");
		urzedySkarboweMap.put("359","Urząd Skarbowy Poznań-Grunwald");
		urzedySkarboweMap.put("361","Urząd Skarbowy Poznań-Jeżyce");
		urzedySkarboweMap.put("362","Urząd Skarbowy Poznań-Nowe Miasto");
		urzedySkarboweMap.put("363","Pierwszy Urząd Skarbowy Poznań");
		urzedySkarboweMap.put("364","Urząd Skarbowy Poznań-Śródmieście");
		urzedySkarboweMap.put("365","Urząd Skarbowy Poznań-Wilda");
		urzedySkarboweMap.put("366","Urząd Skarbowy w Szamotułach");
		urzedySkarboweMap.put("367","Urząd Skarbowy w Śremie");
		urzedySkarboweMap.put("368","Urząd Skarbowy w Środzie Wielkopolskiej");
		urzedySkarboweMap.put("369","Urząd Skarbowy we Wrześni");
		urzedySkarboweMap.put("371","Urząd Skarbowy w Jarosławiu");
		urzedySkarboweMap.put("372","Urząd Skarbowy w Lubaczowie");
		urzedySkarboweMap.put("373","Urząd Skarbowy w Przemyślu");
		urzedySkarboweMap.put("374","Urząd Skarbowy w Przeworsku");
		urzedySkarboweMap.put("375","Urząd Skarbowy w Białobrzegach");
		urzedySkarboweMap.put("376","Urząd Skarbowy w Grójcu");
		urzedySkarboweMap.put("377","Urząd Skarbowy w Kozienicach");
		urzedySkarboweMap.put("378","Pierwszy Urząd Skarbowy w Radomiu");
		urzedySkarboweMap.put("379","Urząd Skarbowy w Szydłowcu");
		urzedySkarboweMap.put("381","Urząd Skarbowy w Zwoleniu");
		urzedySkarboweMap.put("382","Urząd Skarbowy w Kolbuszowej");
		urzedySkarboweMap.put("383","Urząd Skarbowy w Leżajsku");
		urzedySkarboweMap.put("384","Urząd Skarbowy w Łańcucie");
		urzedySkarboweMap.put("385","Urząd Skarbowy w Mielcu");
		urzedySkarboweMap.put("386","Urząd Skarbowy w Ropczycach");
		urzedySkarboweMap.put("387","Urząd Skarbowy w Rzeszowie");
		urzedySkarboweMap.put("388","Urząd Skarbowy w Strzyżowie");
		urzedySkarboweMap.put("389","Urząd Skarbowy w Garwolinie");
		urzedySkarboweMap.put("391","Urząd Skarbowy w Łukowie");
		urzedySkarboweMap.put("392","Urząd Skarbowy w Mińsku Mazowieckim");
		urzedySkarboweMap.put("393","Urząd Skarbowy w Siedlcach");
		urzedySkarboweMap.put("394","Urząd Skarbowy w Sokołowie Podlaskim");
		urzedySkarboweMap.put("395","Urząd Skarbowy w Węgrowie");
		urzedySkarboweMap.put("396","Urząd Skarbowy w Łasku");
		urzedySkarboweMap.put("397","Urząd Skarbowy w Poddębicach");
		urzedySkarboweMap.put("398","Urząd Skarbowy w Sieradzu");
		urzedySkarboweMap.put("399","Urząd Skarbowy w Wieluniu");
		urzedySkarboweMap.put("411","Urząd Skarbowy w Zduńskiej Woli");
		urzedySkarboweMap.put("412","Urząd Skarbowy w Brzezinach");
		urzedySkarboweMap.put("413","Urząd Skarbowy w Łowiczu");
		urzedySkarboweMap.put("414","Urząd Skarbowy w Rawie Mazowieckiej");
		urzedySkarboweMap.put("415","Urząd Skarbowy w Skierniewicach");
		urzedySkarboweMap.put("416","Urząd Skarbowy w Sochaczewie");
		urzedySkarboweMap.put("417","Urząd Skarbowy w Żyrardowie");
		urzedySkarboweMap.put("418","Urząd Skarbowy w Bytowie");
		urzedySkarboweMap.put("419","Urząd Skarbowy w Człuchowie");
		urzedySkarboweMap.put("421","Urząd Skarbowy w Lęborku");
		urzedySkarboweMap.put("422","Urząd Skarbowy w Słupsku");
		urzedySkarboweMap.put("423","Urząd Skarbowy w Augustowie");
		urzedySkarboweMap.put("424","Urząd Skarbowy w Ełku");
		urzedySkarboweMap.put("425","Urząd Skarbowy w Giżycku");
		urzedySkarboweMap.put("426","Urząd Skarbowy w Olecku");
		urzedySkarboweMap.put("427","Urząd Skarbowy w Piszu");
		urzedySkarboweMap.put("428","Urząd Skarbowy w Suwałkach");
		urzedySkarboweMap.put("429","Urząd Skarbowy w Goleniowie");
		urzedySkarboweMap.put("431","Urząd Skarbowy w Gryficach");
		urzedySkarboweMap.put("432","Urząd Skarbowy w Gryfinie");
		urzedySkarboweMap.put("433","Urząd Skarbowy w Pyrzycach");
		urzedySkarboweMap.put("434","Urząd Skarbowy w Stargardzie Szczecińskim");
		urzedySkarboweMap.put("435","Pierwszy Urząd Skarbowy w Szczecinie");
		urzedySkarboweMap.put("436","Drugi Urząd Skarbowy w Szczecinie");
		urzedySkarboweMap.put("437","Urząd Skarbowy w Świnoujściu");
		urzedySkarboweMap.put("438","Urząd Skarbowy w Janowie Lubelskim");
		urzedySkarboweMap.put("439","Urząd Skarbowy w Opatowie");
		urzedySkarboweMap.put("441","Urząd Skarbowy w Sandomierzu");
		urzedySkarboweMap.put("442","Urząd Skarbowy w Stalowej Woli");
		urzedySkarboweMap.put("443","Urząd Skarbowy w Staszowie");
		urzedySkarboweMap.put("444","Urząd Skarbowy w Tarnobrzegu");
		urzedySkarboweMap.put("445","Urząd Skarbowy w Bochni");
		urzedySkarboweMap.put("446","Urząd Skarbowy w Brzesku");
		urzedySkarboweMap.put("447","Urząd Skarbowy w Dąbrowie Tarnowskiej");
		urzedySkarboweMap.put("448","Urząd Skarbowy w Dębicy");
		urzedySkarboweMap.put("449","Pierwszy Urząd Skarbowy w Tarnowie");
		urzedySkarboweMap.put("451","Urząd Skarbowy w Brodnicy");
		urzedySkarboweMap.put("452","Urząd Skarbowy w Chełmnie");
		urzedySkarboweMap.put("453","Urząd Skarbowy w Grudziądzu");
		urzedySkarboweMap.put("454","Urząd Skarbowy w Nowym Mieście Lubawskim");
		urzedySkarboweMap.put("455","Drugi Urząd Skarbowy w Toruniu");
		urzedySkarboweMap.put("456","Urząd Skarbowy w Wąbrzeźnie");
		urzedySkarboweMap.put("457","Urząd Skarbowy w Bystrzycy Kłodzkiej");
		urzedySkarboweMap.put("458","Urząd Skarbowy w Dzierżoniowie");
		urzedySkarboweMap.put("459","Urząd Skarbowy w Kłodzku");
		urzedySkarboweMap.put("461","Urząd Skarbowy w Nowej Rudzie");
		urzedySkarboweMap.put("462","Urząd Skarbowy w Świdnicy");
		urzedySkarboweMap.put("463","Urząd Skarbowy w Wałbrzychu");
		urzedySkarboweMap.put("464","Urząd Skarbowy w Ząbkowicach Śląskich");
		urzedySkarboweMap.put("465","Urząd Skarbowy w Aleksandrowie Kujawskim");
		urzedySkarboweMap.put("466","Urząd Skarbowy w Lipnie");
		urzedySkarboweMap.put("467","Urząd Skarbowy w Radziejowie");
		urzedySkarboweMap.put("468","Urząd Skarbowy w Rypinie");
		urzedySkarboweMap.put("469","Urząd Skarbowy we Włocławku");
		urzedySkarboweMap.put("471","Urząd Skarbowy Wrocław-Fabryczna");
		urzedySkarboweMap.put("472","Urząd Skarbowy Wrocław-Krzyki");
		urzedySkarboweMap.put("473","Urząd Skarbowy Wrocław-Psie Pole");
		urzedySkarboweMap.put("474","Urząd Skarbowy Wrocław-Stare Miasto");
		urzedySkarboweMap.put("475","Pierwszy Urząd Skarbowy we Wrocławiu");
		urzedySkarboweMap.put("476","Drugi Urząd Skarbowy Wrocław-Śródmieście");
		urzedySkarboweMap.put("477","Urząd Skarbowy w Miliczu");
		urzedySkarboweMap.put("478","Urząd Skarbowy w Oleśnicy");
		urzedySkarboweMap.put("479","Urząd Skarbowy w Oławie");
		urzedySkarboweMap.put("481","Urząd Skarbowy w Strzelnie");
		urzedySkarboweMap.put("482","Urząd Skarbowy w Środzie Śląskiej");
		urzedySkarboweMap.put("483","Urząd Skarbowy w Trzebnicy");
		urzedySkarboweMap.put("484","Urząd Skarbowy w Biłgoraju");
		urzedySkarboweMap.put("485","Urząd Skarbowy w Hrubieszowie");
		urzedySkarboweMap.put("486","Urząd Skarbowy w Tomaszowie Lubelskim");
		urzedySkarboweMap.put("487","Urząd Skarbowy w Zamościu");
		urzedySkarboweMap.put("488","Urząd Skarbowy w Krośnie Odrzańskim");
		urzedySkarboweMap.put("489","Urząd Skarbowy w Nowej Soli");
		urzedySkarboweMap.put("491","Urząd Skarbowy w Świebodzinie");
		urzedySkarboweMap.put("492","Urząd Skarbowy w Wolsztynie");
		urzedySkarboweMap.put("493","Pierwszy Urząd Skarbowy w Zielonej Górze");
		urzedySkarboweMap.put("494","Urząd Skarbowy w Żaganiu");
		urzedySkarboweMap.put("495","Urząd Skarbowy w Żarach");
		urzedySkarboweMap.put("496","Urząd Skarbowy w Łosicach");
		urzedySkarboweMap.put("497","Urząd Skarbowy w Łosicach");
		urzedySkarboweMap.put("498","Urząd Skarbowy w Piekarach Śląskich");
		urzedySkarboweMap.put("499","Drugi Urząd Skarbowy w Koszalinie");
		urzedySkarboweMap.put("501","Urząd Skarbowy W Górze");
		urzedySkarboweMap.put("502","Urząd Skarbowy W Polkowicach");
		urzedySkarboweMap.put("503","Urząd Skarbowy W Golubiu-Dobrzyniu");
		urzedySkarboweMap.put("504","Urząd Skarbowy W Sepólnie Krajeńskim");
		urzedySkarboweMap.put("505","Urząd Skarbowy W Łęcznej");
		urzedySkarboweMap.put("506","Urząd Skarbowy W Rykach");
		urzedySkarboweMap.put("507","Urząd Skarbowy W Łęczycy");
		urzedySkarboweMap.put("508","Urząd Skarbowy W Pajęcznie");
		urzedySkarboweMap.put("509","Urząd Skarbowy W Lipsku");
		urzedySkarboweMap.put("511","Urząd Skarbowy w Żurominie");
		urzedySkarboweMap.put("512","Urząd Skarbowy w Żurominie");
		urzedySkarboweMap.put("513","Urząd Skarbowy w Lesznie");
		urzedySkarboweMap.put("514","Urząd Skarbowy w Ostrzeszowie");
		urzedySkarboweMap.put("516","Urząd Skarbowy w Ostrzeszowie");
		urzedySkarboweMap.put("519","Urząd Skarbowy w Legionowie");
		urzedySkarboweMap.put("521","Urząd Skarbowy Warszawa-Mokotów");
		urzedySkarboweMap.put("522","Urząd Skarbowy Warszawa-Bemowo");
		urzedySkarboweMap.put("523","Urząd Skarbowy Warszawa-Praga");
		urzedySkarboweMap.put("524","Urząd Skarbowy Warszawa-Targówek");
		urzedySkarboweMap.put("525","Pierwszy Urząd Skarbowy Warszawa-Śródmieście");
		urzedySkarboweMap.put("526","Drugi Urząd Skarbowy Warszawa-Śródmieście");
		urzedySkarboweMap.put("527","Urząd Skarbowy Warszawa-Wola");
		urzedySkarboweMap.put("528","Urząd Skarbowy Warszawa-Bielany");
		urzedySkarboweMap.put("529","Urząd Skarbowy w Grodzisku Mazowieckim");
		urzedySkarboweMap.put("531","Urząd Skarbowy w Nowym Dworze Mazowieckim");
		urzedySkarboweMap.put("532","Urząd Skarbowy w Otwocku");
		urzedySkarboweMap.put("533","Urząd Skarbowy w Piasecznie");
		urzedySkarboweMap.put("534","Urząd Skarbowy w Pruszkowie");
		urzedySkarboweMap.put("535","Urząd Skarbowy w Wołominie");
		urzedySkarboweMap.put("536","Urząd Skarbowy w Legionowie");
		urzedySkarboweMap.put("537","Urząd Skarbowy w Białej Podlaskiej");
		urzedySkarboweMap.put("538","Urząd Skarbowy w Radzyniu Podlaskim");
		urzedySkarboweMap.put("539","Urząd Skarbowy w Parczewie");
		urzedySkarboweMap.put("541","Filia US w Białej Podlaskiej/Łosice");
		urzedySkarboweMap.put("542","Pierwszy Urząd Skarbowy w Białymstoku");
		urzedySkarboweMap.put("543","Urząd Skarbowy w Bielsku Podlaskim");
		urzedySkarboweMap.put("544","Urząd Skarbowy w Siemiatyczach");
		urzedySkarboweMap.put("545","Urząd Skarbowy w Sokółce");
		urzedySkarboweMap.put("546","Urząd Skarbowy w Mońkach");
		urzedySkarboweMap.put("547","Pierwszy Urząd Skarbowy w Bielsku-Białej");
		urzedySkarboweMap.put("548","Urząd Skarbowy w Cieszynie");
		urzedySkarboweMap.put("549","Urząd Skarbowy w Oświęcimiu");
		urzedySkarboweMap.put("551","Urząd Skarbowy w Wadowicach");
		urzedySkarboweMap.put("552","Urząd Skarbowy w Suchej Beskidzkiej");
		urzedySkarboweMap.put("553","Urząd Skarbowy w Żywcu");
		urzedySkarboweMap.put("554","Pierwszy Urząd Skarbowy w Bydgoszczy");
		urzedySkarboweMap.put("555","Urząd Skarbowy w Chojnicach");
		urzedySkarboweMap.put("556","Urząd Skarbowy w Inowrocławiu");
		urzedySkarboweMap.put("557","Urząd Skarbowy w Mogilnie");
		urzedySkarboweMap.put("558","Urząd Skarbowy w Nakle nad Notecią");
		urzedySkarboweMap.put("559","Urząd Skarbowy w Świeciu");
		urzedySkarboweMap.put("561","Urząd Skarbowy w Tucholi");
		urzedySkarboweMap.put("562","Urząd Skarbowy w Żninie");
		urzedySkarboweMap.put("563","Urząd Skarbowy w Chełmie");
		urzedySkarboweMap.put("564","Urząd Skarbowy w Krasnymstawie");
		urzedySkarboweMap.put("565","Urząd Skarbowy we Włodawie");
		urzedySkarboweMap.put("566","Urząd Skarbowy w Ciechanowie");
		urzedySkarboweMap.put("567","Urząd Skarbowy w Płońsku");
		urzedySkarboweMap.put("568","Urząd Skarbowy w Pułtusku");
		urzedySkarboweMap.put("569","Urząd Skarbowy w Mławie");
		urzedySkarboweMap.put("571","Urząd Skarbowy w Działdowie");
		urzedySkarboweMap.put("572","Filia US w Mławie/Żuromin");
		urzedySkarboweMap.put("573","Pierwszy Urząd Skarbowy w Częstochowie");
		urzedySkarboweMap.put("574","Urząd Skarbowy w Kłobucku");
		urzedySkarboweMap.put("575","Urząd Skarbowy w Lublińcu");
		urzedySkarboweMap.put("576","Urząd Skarbowy w Oleśnie");
		urzedySkarboweMap.put("577","Urząd Skarbowy w Myszkowie");
		urzedySkarboweMap.put("578","Urząd Skarbowy w Elblągu");
		urzedySkarboweMap.put("579","Urząd Skarbowy w Malborku");
		urzedySkarboweMap.put("581","Urząd Skarbowy w Kwidzynie");
		urzedySkarboweMap.put("582","Urząd Skarbowy w Braniewie");
		urzedySkarboweMap.put("583","Pierwszy Urząd Skarbowy w Gdańsku");
		urzedySkarboweMap.put("584","Drugi Urząd Skarbowy w Gdańsku");
		urzedySkarboweMap.put("585","Urząd Skarbowy w Sopocie");
		urzedySkarboweMap.put("586","Pierwszy Urząd Skarbowy w Gdyni");
		urzedySkarboweMap.put("587","Urząd Skarbowy w Pucku");
		urzedySkarboweMap.put("588","Urząd Skarbowy w Wejherowie");
		urzedySkarboweMap.put("589","Urząd Skarbowy w Kartuzach");
		urzedySkarboweMap.put("591","Urząd Skarbowy w Kościerzynie");
		urzedySkarboweMap.put("592","Urząd Skarbowy w Starogardzie Gdańskim");
		urzedySkarboweMap.put("593","Urząd Skarbowy w Tczewie");
		urzedySkarboweMap.put("594","Urząd Skarbowy w Choszcznie");
		urzedySkarboweMap.put("595","Urząd Skarbowy w Międzychodzie");
		urzedySkarboweMap.put("596","Urząd Skarbowy w Międzyrzeczu");
		urzedySkarboweMap.put("597","Urząd Skarbowy w Myśliborzu");
		urzedySkarboweMap.put("598","Urząd Skarbowy w Słubicach");
		urzedySkarboweMap.put("599","Urząd Skarbowy w Gorzowie Wielkopolskim");
		urzedySkarboweMap.put("601","Urząd Skarbowy w Przysusze");
		urzedySkarboweMap.put("602","Urząd Skarbowy w Nisku");
		urzedySkarboweMap.put("603","Urząd Skarbowy w Hajnówce");
		urzedySkarboweMap.put("604","Urząd Skarbowy w Pruszczu Gdańskim");
		urzedySkarboweMap.put("605","Urząd Skarbowy w Kazimierzy Wielkiej");
		urzedySkarboweMap.put("606","Urząd Skarbowy w Obornikach");
		urzedySkarboweMap.put("607","Urząd Skarbowy w Chodzieży");
		urzedySkarboweMap.put("608","Urząd Skarbowy w Pleszewie");
		urzedySkarboweMap.put("609","Urząd Skarbowy we Włoszczowie");
		urzedySkarboweMap.put("611","Urząd Skarbowy w Jeleniej-Górze");
		urzedySkarboweMap.put("612","Urząd Skarbowy w Bolesławcu");
		urzedySkarboweMap.put("613","Urząd Skarbowy w Lubaniu");
		urzedySkarboweMap.put("614","Urząd Skarbowy w Kamiennej-Górze");
		urzedySkarboweMap.put("615","Urząd Skarbowy w Zgorzelcu");
		urzedySkarboweMap.put("616","Urząd Skarbowy w Lwówku ŚLąskim");
		urzedySkarboweMap.put("617","Urząd Skarbowy w Jarocinie");
		urzedySkarboweMap.put("618","Pierwszy Urząd Skarbowy w Kaliszu");
		urzedySkarboweMap.put("619","Urząd Skarbowy w Kępnie");
		urzedySkarboweMap.put("621","Urząd Skarbowy w Krotoszynie");
		urzedySkarboweMap.put("622","Urząd Skarbowy w Ostrowie Wielkopolskim");
		urzedySkarboweMap.put("623","Urząd Skarbowy w Piekarach Śląskich");
		urzedySkarboweMap.put("624","Drugi Urząd Skarbowy w Koszalinie");
		urzedySkarboweMap.put("625","Urząd Skarbowy w Będzinie");
		urzedySkarboweMap.put("626","Urząd Skarbowy w Bytomiu");
		urzedySkarboweMap.put("627","Urząd Skarbowy w Chorzowie");
		urzedySkarboweMap.put("628","Urząd Skarbowy w Chrzanowie");
		urzedySkarboweMap.put("629","Urząd Skarbowy w Dąbrowie Górniczej");
		urzedySkarboweMap.put("631","Pierwszy Urząd Skarbowy w Gliwicach");
		urzedySkarboweMap.put("632","Urząd Skarbowy w Jaworznie");
		urzedySkarboweMap.put("633","Urząd Skarbowy w Jastrzębiu-Zdroju");
		urzedySkarboweMap.put("634","Pierwszy Urząd Skarbowy w Katowicach");
		urzedySkarboweMap.put("635","Urząd Skarbowy w Mikołowie");
		urzedySkarboweMap.put("636","Urząd Skarbowy w Mysłowicach");
		urzedySkarboweMap.put("637","Urząd Skarbowy w Olkuszu");
		urzedySkarboweMap.put("638","Urząd Skarbowy w Pszczynie");
		urzedySkarboweMap.put("639","Urząd Skarbowy w Raciborzu");
		urzedySkarboweMap.put("641","Urząd Skarbowy w Rudzie Śląskiej");
		urzedySkarboweMap.put("642","Urząd Skarbowy w Rybniku");
		urzedySkarboweMap.put("643","Urząd Skarbowy w Siemianowicach Śląskich");
		urzedySkarboweMap.put("644","Urząd Skarbowy w Sosnowcu");
		urzedySkarboweMap.put("645","Urząd Skarbowy w Tarnowskich Górach");
		urzedySkarboweMap.put("646","Urząd Skarbowy w Tychach");
		urzedySkarboweMap.put("647","Urząd Skarbowy w Wodzisławiu Śląskim");
		urzedySkarboweMap.put("648","Urząd Skarbowy w Zabrzu");
		urzedySkarboweMap.put("649","Urząd Skarbowy w Zawierciu");
		urzedySkarboweMap.put("651","Urząd Skarbowy w Żorach");
		urzedySkarboweMap.put("652","Urząd Skarbowy w Czechowicach Dziedzicach");
		urzedySkarboweMap.put("653","Urząd Skarbowy Tarnowskie Góry filia Piekary Śląskie");
		urzedySkarboweMap.put("654","Filia US w Będzinie/Czeladź");
		urzedySkarboweMap.put("655","Urząd Skarbowy w Busku-Zdroju");
		urzedySkarboweMap.put("656","Urząd Skarbowy w Jędrzejowie");
		urzedySkarboweMap.put("657","Pierwszy Urząd Skarbowy w Kielcach");
		urzedySkarboweMap.put("658","Urząd Skarbowy w Końskich");
		urzedySkarboweMap.put("659","Urząd Skarbowy w Miechowie");
		urzedySkarboweMap.put("661","Urząd Skarbowy w Ostrowcu Świętokrzyskim");
		urzedySkarboweMap.put("662","Urząd Skarbowy w Pińczowie");
		urzedySkarboweMap.put("663","Urząd Skarbowy w Skarżysku Kamiennej");
		urzedySkarboweMap.put("664","Urząd Skarbowy w Starachowicach");
		urzedySkarboweMap.put("665","Urząd Skarbowy w Koninie");
		urzedySkarboweMap.put("666","Urząd Skarbowy w Kole");
		urzedySkarboweMap.put("667","Urząd Skarbowy w Słupcy");
		urzedySkarboweMap.put("668","Urząd Skarbowy w Turku");
		urzedySkarboweMap.put("669","Pierwszy Urząd Skarbowy w Koszalinie");
		urzedySkarboweMap.put("671","Urząd Skarbowy w Kołobrzegu");
		urzedySkarboweMap.put("672","Urząd Skarbowy w Białogardzie");
		urzedySkarboweMap.put("673","Urząd Skarbowy w Szczecinku");
		urzedySkarboweMap.put("674","Urząd Skarbowy w Drawsku Pomorskim");
		urzedySkarboweMap.put("675","Urząd Skarbowy Kraków-Śródmieście");
		urzedySkarboweMap.put("676","Urząd Skarbowy Kraków-Stare Miasto");
		urzedySkarboweMap.put("677","Urząd Skarbowy Kraków-Krowodrza");
		urzedySkarboweMap.put("678","Urząd Skarbowy Kraków-Nowa Huta");
		urzedySkarboweMap.put("679","Urząd Skarbowy Kraków-Podgórze");
		urzedySkarboweMap.put("681","Urząd Skarbowy w Myślenicach");
		urzedySkarboweMap.put("682","Urząd Skarbowy w Proszowicach");
		urzedySkarboweMap.put("683","Urząd Skarbowy w Wieliczce");
		urzedySkarboweMap.put("684","Urząd Skarbowy w Krośnie");
		urzedySkarboweMap.put("685","Urząd Skarbowy w Jaśle");
		urzedySkarboweMap.put("686","Urząd Skarbowy w Brzozowie");
		urzedySkarboweMap.put("687","Urząd Skarbowy w Sanoku");
		urzedySkarboweMap.put("688","Urząd Skarbowy w Lesku");
		urzedySkarboweMap.put("689","Urząd Skarbowy w Ustrzykach Dolnych");
		urzedySkarboweMap.put("691","Urząd Skarbowy w Legnicy");
		urzedySkarboweMap.put("692","Urząd Skarbowy w Lubinie");
		urzedySkarboweMap.put("693","Urząd Skarbowy w Głogowie");
		urzedySkarboweMap.put("694","Urząd Skarbowy w Złotoryi");
		urzedySkarboweMap.put("695","Urząd Skarbowy w Jaworze");
		urzedySkarboweMap.put("696","Urząd Skarbowy w Gostyniu");
		urzedySkarboweMap.put("697","Urząd Skarbowy w Lesznie");
		urzedySkarboweMap.put("698","Urząd Skarbowy w Kościanie");
		urzedySkarboweMap.put("699","Urząd Skarbowy w Rawiczu");
		urzedySkarboweMap.put("701","Trzeci Urząd Skarbowy Warszawa-Śródmieście");
		urzedySkarboweMap.put("711","Urząd Skarbowy w Lesznie");
		urzedySkarboweMap.put("712","Pierwszy Urząd Skarbowy w Lublinie");
		urzedySkarboweMap.put("713","Drugi Urząd Skarbowy w Lublinie");
		urzedySkarboweMap.put("714","Urząd Skarbowy w Lubartowie");
		urzedySkarboweMap.put("715","Urząd Skarbowy w Kraśniku");
		urzedySkarboweMap.put("716","Urząd Skarbowy w Puławach");
		urzedySkarboweMap.put("717","Urząd Skarbowy w Opolu Lubelskim");
		urzedySkarboweMap.put("718","Urząd Skarbowy w Łomży");
		urzedySkarboweMap.put("719","Urząd Skarbowy w Grajewie");
		urzedySkarboweMap.put("721","Urząd Skarbowy w Kolnie");
		urzedySkarboweMap.put("722","Urząd Skarbowy w Wysokiem Mazowieckiem");
		urzedySkarboweMap.put("723","Urząd Skarbowy w Zambrowie");
		urzedySkarboweMap.put("724","Pierwszy Urząd Skarbowy Łódź-Śródmieście");
		urzedySkarboweMap.put("725","Urząd Skarbowy Łódź-Śródmieście");
		urzedySkarboweMap.put("726","Pierwszy Urząd Skarbowy Łódź-Bałuty");
		urzedySkarboweMap.put("727","Urząd Skarbowy Łódź-Polesie");
		urzedySkarboweMap.put("728","Urząd Skarbowy Łódź-Widzew");
		urzedySkarboweMap.put("729","Pierwszy Urząd Skarbowy Łódź-Górna");
		urzedySkarboweMap.put("731","Urząd Skarbowy w Pabianicach");
		urzedySkarboweMap.put("732","Urząd Skarbowy w Zgierzu");
		urzedySkarboweMap.put("733","Urząd Skarbowy w Głownie");
		urzedySkarboweMap.put("734","Urząd Skarbowy w Nowym Sączu");
		urzedySkarboweMap.put("735","Urząd Skarbowy w Nowym Targu");
		urzedySkarboweMap.put("736","Urząd Skarbowy w Zakopanem");
		urzedySkarboweMap.put("737","Urząd Skarbowy w Limanowej");
		urzedySkarboweMap.put("738","Urząd Skarbowy w Gorlicach");
		urzedySkarboweMap.put("739","Urząd Skarbowy w Olsztynie");
		urzedySkarboweMap.put("741","Urząd Skarbowy w Ostródzie");
		urzedySkarboweMap.put("742","Urząd Skarbowy w Kętrzynie");
		urzedySkarboweMap.put("743","Urząd Skarbowy w Bartoszycach");
		urzedySkarboweMap.put("744","Urząd Skarbowy w Iławie");
		urzedySkarboweMap.put("745","Urząd Skarbowy w Szczytnie");
		urzedySkarboweMap.put("746","Filia US w Szczytnie/Nidzica");
		urzedySkarboweMap.put("747","Urząd Skarbowy w Brzegu");
		urzedySkarboweMap.put("748","Urząd Skarbowy w Głubczycach");
		urzedySkarboweMap.put("749","Urząd Skarbowy w Kędzierzynie-Koźlu");
		urzedySkarboweMap.put("751","Urząd Skarbowy w Kluczborku");
		urzedySkarboweMap.put("752","Urząd Skarbowy w Namysłowie");
		urzedySkarboweMap.put("753","Urząd Skarbowy w Nysie");
		urzedySkarboweMap.put("754","Pierwszy Urząd Skarbowy w Opolu");
		urzedySkarboweMap.put("755","Urząd Skarbowy w Prudniku");
		urzedySkarboweMap.put("756","Urząd Skarbowy w Strzelcach Opolskich");
		urzedySkarboweMap.put("757","Urząd Skarbowy w Makowie Mazowieckim");
		urzedySkarboweMap.put("758","Urząd Skarbowy w Ostrołęce");
		urzedySkarboweMap.put("759","Urząd Skarbowy w Ostrowi Mazowieckiej");
		urzedySkarboweMap.put("761","Urząd Skarbowy w Przasnyszu");
		urzedySkarboweMap.put("762","Urząd Skarbowy w Wyszkowie");
		urzedySkarboweMap.put("763","Urząd Skarbowy w Czarnkowie");
		urzedySkarboweMap.put("764","Urząd Skarbowy w Pile");
		urzedySkarboweMap.put("765","Urząd Skarbowy w Wałczu");
		urzedySkarboweMap.put("766","Urząd Skarbowy w Wągrowcu");
		urzedySkarboweMap.put("767","Urząd Skarbowy w Złotowie");
		urzedySkarboweMap.put("768","Urząd Skarbowy w Opocznie");
		urzedySkarboweMap.put("769","Urząd Skarbowy w Bełchatowie");
		urzedySkarboweMap.put("771","Urząd Skarbowy w Piotrkowie Trybunalskim");
		urzedySkarboweMap.put("772","Urząd Skarbowy w Radomsku");
		urzedySkarboweMap.put("773","Urząd Skarbowy w Tomaszowie Mazowieckim");
		urzedySkarboweMap.put("774","Urząd Skarbowy w Płocku");
		urzedySkarboweMap.put("775","Urząd Skarbowy w Kutnie");
		urzedySkarboweMap.put("776","Urząd Skarbowy w Sierpcu");
		urzedySkarboweMap.put("777","Pierwszy Urząd Skarbowy Poznań");
		urzedySkarboweMap.put("778","Urząd Skarbowy Poznań-Śródmieście");
		urzedySkarboweMap.put("779","Urząd Skarbowy Poznań-Grunwald");
		urzedySkarboweMap.put("781","Urząd Skarbowy Poznań-Jeżyce");
		urzedySkarboweMap.put("782","Urząd Skarbowy Poznań-Nowe Miasto");
		urzedySkarboweMap.put("783","Urząd Skarbowy Poznań-Wilda");
		urzedySkarboweMap.put("784","Urząd Skarbowy w Gnieźnie");
		urzedySkarboweMap.put("785","Urząd Skarbowy w Śremie");
		urzedySkarboweMap.put("786","Urząd Skarbowy w Środzie Wielkopolskiej");
		urzedySkarboweMap.put("787","Urząd Skarbowy w Szamotułach");
		urzedySkarboweMap.put("788","Urząd Skarbowy w Nowym Tomyślu");
		urzedySkarboweMap.put("789","Urząd Skarbowy we Wrześni");
		urzedySkarboweMap.put("791","Filia US w Nowym Tomyślu/Grodzisk Wlkp.");
		urzedySkarboweMap.put("792","Urząd Skarbowy w Jarosławiu");
		urzedySkarboweMap.put("793","Urząd Skarbowy w Lubaczowie");
		urzedySkarboweMap.put("794","Urząd Skarbowy w Przeworsku");
		urzedySkarboweMap.put("795","Urząd Skarbowy w Przemyślu");
		urzedySkarboweMap.put("796","Pierwszy Urząd Skarbowy w Radomiu");
		urzedySkarboweMap.put("797","Urząd Skarbowy w Grójcu");
		urzedySkarboweMap.put("798","Urząd Skarbowy w Białobrzegach");
		urzedySkarboweMap.put("799","Urząd Skarbowy w Szydłowcu");
		urzedySkarboweMap.put("811","Urząd Skarbowy w Zwoleniu");
		urzedySkarboweMap.put("812","Urząd Skarbowy w Kozienicach");
		urzedySkarboweMap.put("813","Urząd Skarbowy w Rzeszowie");
		urzedySkarboweMap.put("814","Urząd Skarbowy w Kolbuszowej");
		urzedySkarboweMap.put("815","Urząd Skarbowy w Łańcucie");
		urzedySkarboweMap.put("816","Urząd Skarbowy w Leżajsku");
		urzedySkarboweMap.put("817","Urząd Skarbowy w Mielcu");
		urzedySkarboweMap.put("818","Urząd Skarbowy w Ropczycach");
		urzedySkarboweMap.put("819","Urząd Skarbowy w Strzyżowie");
		urzedySkarboweMap.put("821","Urząd Skarbowy w Siedlcach");
		urzedySkarboweMap.put("822","Urząd Skarbowy w Mińsku Mazowieckim");
		urzedySkarboweMap.put("823","Urząd Skarbowy w Sokołowie Podlaskim");
		urzedySkarboweMap.put("824","Urząd Skarbowy w Węgrowie");
		urzedySkarboweMap.put("825","Urząd Skarbowy w Łukowie");
		urzedySkarboweMap.put("826","Urząd Skarbowy w Garwolinie");
		urzedySkarboweMap.put("827","Urząd Skarbowy w Sieradzu");
		urzedySkarboweMap.put("828","Urząd Skarbowy w Poddębicach");
		urzedySkarboweMap.put("829","Urząd Skarbowy w Zduńskiej Woli");
		urzedySkarboweMap.put("831","Urząd Skarbowy w Łasku");
		urzedySkarboweMap.put("832","Urząd Skarbowy w Wieluniu");
		urzedySkarboweMap.put("833","Urząd Skarbowy w Brzezinach");
		urzedySkarboweMap.put("834","Urząd Skarbowy w Łowiczu");
		urzedySkarboweMap.put("835","Urząd Skarbowy w Rawie Mazowieckiej");
		urzedySkarboweMap.put("836","Urząd Skarbowy w Skierniewicach");
		urzedySkarboweMap.put("837","Urząd Skarbowy w Sochaczewie");
		urzedySkarboweMap.put("838","Urząd Skarbowy w Żyrardowie");
		urzedySkarboweMap.put("839","Urząd Skarbowy w Słupsku");
		urzedySkarboweMap.put("841","Urząd Skarbowy w Lęborku");
		urzedySkarboweMap.put("842","Urząd Skarbowy w Bytowie");
		urzedySkarboweMap.put("843","Urząd Skarbowy w Człuchowie");
		urzedySkarboweMap.put("844","Urząd Skarbowy w Suwałkach");
		urzedySkarboweMap.put("845","Urząd Skarbowy w Giżycku");
		urzedySkarboweMap.put("846","Urząd Skarbowy w Augustowie");
		urzedySkarboweMap.put("847","Urząd Skarbowy w Olecku");
		urzedySkarboweMap.put("848","Urząd Skarbowy w Ełku");
		urzedySkarboweMap.put("849","Urząd Skarbowy w Piszu");
		urzedySkarboweMap.put("851","Pierwszy Urząd Skarbowy w Szczecinie");
		urzedySkarboweMap.put("852","Drugi Urząd Skarbowy w Szczecinie");
		urzedySkarboweMap.put("853","Urząd Skarbowy w Pyrzycach");
		urzedySkarboweMap.put("854","Urząd Skarbowy w Starogardzie Szczecińskim");
		urzedySkarboweMap.put("855","Urząd Skarbowy w Świnoujściu");
		urzedySkarboweMap.put("856","Urząd Skarbowy w Goleniowie");
		urzedySkarboweMap.put("857","Urząd Skarbowy w Gryficach");
		urzedySkarboweMap.put("858","Urząd Skarbowy w Gryfinie");
		urzedySkarboweMap.put("859","Filia US w Goleniowie/Nowogard");
		urzedySkarboweMap.put("861","Filia US w Gryficach/Kamień Pom.");
		urzedySkarboweMap.put("862","Urząd Skarbowy w Janowie Lubelskim");
		urzedySkarboweMap.put("863","Urząd Skarbowy w Opatowie");
		urzedySkarboweMap.put("864","Urząd Skarbowy w Sandomierzu");
		urzedySkarboweMap.put("865","Urząd Skarbowy w Stalowej Woli");
		urzedySkarboweMap.put("866","Urząd Skarbowy w Staszowie");
		urzedySkarboweMap.put("867","Urząd Skarbowy w Tarnobrzegu");
		urzedySkarboweMap.put("868","Urząd Skarbowy w Bochni");
		urzedySkarboweMap.put("869","Urząd Skarbowy w Brzesku");
		urzedySkarboweMap.put("871","Urząd Skarbowy w Dąbrowie Tarnowskiej");
		urzedySkarboweMap.put("872","Urząd Skarbowy w Dębicy");
		urzedySkarboweMap.put("873","Pierwszy Urząd Skarbowy w Tarnowie");
		urzedySkarboweMap.put("874","Urząd Skarbowy w Brodnicy");
		urzedySkarboweMap.put("875","Urząd Skarbowy w Chełmnie");
		urzedySkarboweMap.put("876","Urząd Skarbowy w Grudziądzu");
		urzedySkarboweMap.put("877","Urząd Skarbowy w Nowym Mieście Lubawskim");
		urzedySkarboweMap.put("878","Urząd Skarbowy w Wąbrzeźnie");
		urzedySkarboweMap.put("879","Drugi Urząd Skarbowy w Toruniu");
		urzedySkarboweMap.put("881","Urząd Skarbowy w Bystrzycy Kłodzkiej");
		urzedySkarboweMap.put("882","Urząd Skarbowy w Dzierżoniowie");
		urzedySkarboweMap.put("883","Urząd Skarbowy w Kłodzku");
		urzedySkarboweMap.put("884","Urząd Skarbowy w Świdnicy");
		urzedySkarboweMap.put("885","Urząd Skarbowy w Nowej Rudzie");
		urzedySkarboweMap.put("886","Urząd Skarbowy w Wałbrzychu");
		urzedySkarboweMap.put("887","Urząd Skarbowy w Ząbkowicach Śląskich");
		urzedySkarboweMap.put("888","Urząd Skarbowy w Włocławku");
		urzedySkarboweMap.put("889","Urząd Skarbowy w Radziejowie");
		urzedySkarboweMap.put("891","Urząd Skarbowy w Aleksandrowie Kujawskim");
		urzedySkarboweMap.put("892","Urząd Skarbowy w Rypinie");
		urzedySkarboweMap.put("893","Urząd Skarbowy w Lipnie");
		urzedySkarboweMap.put("894","Urząd Skarbowy Wrocław-Fabryczna");
		urzedySkarboweMap.put("895","Urząd Skarbowy Wrocław-Psie Pole");
		urzedySkarboweMap.put("896","Pierwszy Urząd Skarbowy we Wrocławiu");
		urzedySkarboweMap.put("897","Urząd Skarbowy Wrocław-Stare Miasto");
		urzedySkarboweMap.put("898","Drugi Urząd Skarbowy Wrocław-Śródmieście");
		urzedySkarboweMap.put("899","Urząd Skarbowy Wrocław-Krzyki");
		urzedySkarboweMap.put("911","Urząd Skarbowy w Oleśnicy");
		urzedySkarboweMap.put("912","Urząd Skarbowy w Oławie");
		urzedySkarboweMap.put("913","Urząd Skarbowy w Środzie Wielkopolskiej");
		urzedySkarboweMap.put("914","Urząd Skarbowy w Strzelnie");
		urzedySkarboweMap.put("915","Urząd Skarbowy w Trzebnicy");
		urzedySkarboweMap.put("916","Urząd Skarbowy w Miliczu");
		urzedySkarboweMap.put("917","Filia US w Trzebnicy/Wołów");
		urzedySkarboweMap.put("918","Urząd Skarbowy w Biłgoraju");
		urzedySkarboweMap.put("919","Urząd Skarbowy w Hrubieszowie");
		urzedySkarboweMap.put("921","Urząd Skarbowy w Tomaszowie Lubelskim");
		urzedySkarboweMap.put("922","Urząd Skarbowy w Zamościu");
		urzedySkarboweMap.put("923","Urząd Skarbowy w Wolsztynie");
		urzedySkarboweMap.put("924","Urząd Skarbowy w Żaganiu");
		urzedySkarboweMap.put("925","Urząd Skarbowy w Nowej Soli");
		urzedySkarboweMap.put("926","Urząd Skarbowy w Krośnie Odrzańskim");
		urzedySkarboweMap.put("927","Urząd Skarbowy w Świebodzinie");
		urzedySkarboweMap.put("928","Urząd Skarbowy w Żarach");
		urzedySkarboweMap.put("929","Pierwszy Urząd Skarbowy w Zielonej Górze");
		urzedySkarboweMap.put("931","Urząd Skarbowy Warszawa-Ursynów");
		urzedySkarboweMap.put("932","Urząd Skarbowy Warszawa-Wawer");
		urzedySkarboweMap.put("933","Drugi Urząd Skarbowy w Bydgoszczy");
		urzedySkarboweMap.put("934","Drugi Urząd Skarbowy w Katowicach");
		urzedySkarboweMap.put("935","Trzeci Urząd Skarbowy w Szczecinie");
		urzedySkarboweMap.put("936","Pierwszy Urząd Skarbowy w Toruniu");
		urzedySkarboweMap.put("937","Drugi Urząd Skarbowy w Bielsku-Białej");
		urzedySkarboweMap.put("938","Drugi Urząd Skarbowy w Bielsku-Białej");
		urzedySkarboweMap.put("939","Drugi Urząd Skarbowy w Częstochowie");
		urzedySkarboweMap.put("941","Trzeci Urząd Skarbowy w Gdańsku");
		urzedySkarboweMap.put("942","Drugi Urząd Skarbowy w Gdyni");
		urzedySkarboweMap.put("943","Drugi Urząd Skarbowy w Kielcach");
		urzedySkarboweMap.put("944","Urząd Skarbowy Kraków-Dębniki");
		urzedySkarboweMap.put("945","Urząd Skarbowy Kraków-Prądnik");
		urzedySkarboweMap.put("946","Trzeci Urząd Skarbowy w Lublinie");
		urzedySkarboweMap.put("947","Drugi Urząd Skarbowy Łódź-Bałuty");
		urzedySkarboweMap.put("948","Drugi Urząd Skarbowy w Radomiu");
		urzedySkarboweMap.put("949","Drugi Urząd Skarbowy w Częstochowie");
		urzedySkarboweMap.put("951","Urząd Skarbowy Warszawa-Ursynów");
		urzedySkarboweMap.put("952","Urząd Skarbowy Warszawa-Wawer");
		urzedySkarboweMap.put("953","Drugi Urząd Skarbowy w Bydgoszczy");
		urzedySkarboweMap.put("954","Drugi Urząd Skarbowy w Katowicach");
		urzedySkarboweMap.put("955","Trzeci Urząd Skarbowy w Szczecinie");
		urzedySkarboweMap.put("956","Pierwszy Urząd Skarbowy w Toruniu");
		urzedySkarboweMap.put("957","Trzeci Urząd Skarbowy w Gdańsku");
		urzedySkarboweMap.put("958","Drugi Urząd Skarbowy w Gdyni");
		urzedySkarboweMap.put("959","Drugi Urząd Skarbowy w Kielcach");
		urzedySkarboweMap.put("961","Urząd Skarbowy Kraków-Dębniki");
		urzedySkarboweMap.put("962","Urząd Skarbowy Kraków-Prądnik");
		urzedySkarboweMap.put("963","Trzeci Urząd Skarbowy w Lublinie");
		urzedySkarboweMap.put("964","Drugi Urząd Skarbowy Łódź-Bałuty");
		urzedySkarboweMap.put("965","Drugi Urząd Skarbowy w Radomiu");
		urzedySkarboweMap.put("966","Drugi Urząd Skarbowy w Białymstoku");
		urzedySkarboweMap.put("967","Trzeci Urząd Skarbowy w Bydgoszczy");
		urzedySkarboweMap.put("968","Drugi Urząd Skarbowy w Kaliszu");
		urzedySkarboweMap.put("969","Drugi Urząd Skarbowy w Gliwicach");
		urzedySkarboweMap.put("971","Urząd Skarbowy w Gostyninie");
		urzedySkarboweMap.put("972","Urząd Skarbowy Poznań-Winogrady");
		urzedySkarboweMap.put("973","Drugi Urząd Skarbowy w Zielonej-Górze");
		urzedySkarboweMap.put("974","Drugi Urząd Skarbowy w Białymstoku");
		urzedySkarboweMap.put("975","Trzeci Urząd Skarbowy w Bydgoszczy");
		urzedySkarboweMap.put("976","Drugi Urząd Skarbowy w Bydgoszczy");
		urzedySkarboweMap.put("977","Drugi Urząd Skarbowy w Gliwicach");
		urzedySkarboweMap.put("978","Urząd Skarbowy w Gostyninie");
		urzedySkarboweMap.put("979","Urząd Skarbowy Poznań-Winogrady");
		urzedySkarboweMap.put("981","Drugi Urząd Skarbowy w Zielonej Górze");
		urzedySkarboweMap.put("982","Drugi Urząd Skarbowy Łódź-Górna");
		urzedySkarboweMap.put("983","Drugi Urząd Skarbowy Łódź-Górna");
		urzedySkarboweMap.put("984","Urząd Skarbowy w Nidzicy");
		urzedySkarboweMap.put("985","Urząd Skarbowy w Nidzicy");
		urzedySkarboweMap.put("986","Urząd Skarbowy w Kamieniu Pomorskim");
		urzedySkarboweMap.put("987","Urząd Skarbowy w Kamieniu Pomorskim");
		urzedySkarboweMap.put("988","Urząd Skarbowy w Wołowie");
		urzedySkarboweMap.put("989","Urząd Skarbowy w Wołowie");
		urzedySkarboweMap.put("991","Drugi Urząd Skarbowy w Opolu");
		urzedySkarboweMap.put("992","Drugi Urząd Skarbowy w Opolu");
		urzedySkarboweMap.put("993","Drugi Urząd Skarbowy w Tarnowie");
		urzedySkarboweMap.put("994","Drugi Urząd Skarbowy w Tarnowie");
		urzedySkarboweMap.put("995","Urząd Skarbowy w Grodzisku Wielkopolskim");
		urzedySkarboweMap.put("996","Urząd Skarbowy w Grodzisku Wielkopolskim");
		urzedySkarboweMap.put("997","Urząd Skarbowy Wieluń lokalizacja w Wieruszowie");
		urzedySkarboweMap.put("998","Urząd Skarbowy Wieluń lokalizacja w Wieruszowie");
	}
}
